import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import GitHubIcon from '@mui/icons-material/GitHub';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Bio Buddy | Generate your next Twitter bio in seconds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button className={styles.github_button}><GitHubIcon width={30} height={30}/><p>Star on GitHub</p></button>
        <h1>Generate your next Twitter bio in seconds</h1>
        <p>18,421 bios created so far.</p>
        <div className={styles.content_box}>
          <h5>Copy your current bio (or write a few sentences about yourself).</h5>
          <textarea></textarea>
          <h5>Select your vibe.</h5>
          <textarea></textarea>
          <button>Generate your bio.</button>
        </div>
        <div className={styles.footer_box}>
          <h5>Powered by OpenAI and Vercel Edge Functions</h5>
          <ul>
            <li>Twitter</li>
            <li>Github</li>
          </ul>
        </div>
      </main>
    </>
  )
}
